### ISSUE TITLE
Issue with hovers

### ISSUE THREAD

**Issue by michael-carl** [mledour/angular-morris-js#10]
I started using this component, and hovers weren't working as expected;  they hover info was being placed below the chart.  The same thing is happening on the Demo page for the bar & line charts.

I did find a fix, though.  You have to include the morris.css file in the "styles" portion of the angular.json file.  So this isn't really a pull request, as it's not code that needs to be changed, but you could update the Dependancies section of the Get Started page.

**Comment by mledour** [comment]
Doc updated.
thanks
