### ISSUE TITLE
charts not updating when data changes

### ISSUE THREAD

**Issue by SrideviYerneni** [mledour/angular-morris-js#4]
Hi, I'm using Morris charts in angular4 application. Everything works fine but the chart is not getting updated when there is a change in dataset (dynamically). It is getting updated only when the page is refreshed. But I would like to achieve this without refreshing the page. How would I achieve this?

**Comment by mika-el** [comment]
Hi,

Do you change the array ref ?

if not try using ES6 Array spread like this or create a new array

```    
setTimeout(() => {
      this.chartAreaData = [... this.chartAreaData, ... [{ y: '2013', a: 80, b: 70 }]];
}, 1000);
```

**Comment by SrideviYerneni** [comment]
Yes, I'm creating array for the dynamic data.

**Comment by mika-el** [comment]
Can you share the code of your component ?

**Comment by mledour** [comment]
Are you using ChangeDetectionStrategy.OnPush ?
