### ISSUE TITLE
Cannot set ykeys and labels dynamically

### ISSUE THREAD

**Issue by carol-braileanu** [mledour/angular-morris-js#7]
Hello everyone,

I have a chart that loads the ykeys and labels dynamically. I have the following code:
```
  public chartOptions = {
    xkey: 'date',
        ykeys: [],
        labels: [],
        parseTime:false,
        behaveLikeLine: true,
        pointFillColors:['#FAFAFA'],
        pointStrokeColors: ['#CCCCCC'],
        lineColors:['rgba(151,187,205,0.7)'],
        fillOpacity: 0.3,
        resize: true,
  }

this.eventService.getSalesChart(r['id']).subscribe(res => {
        this.chartOptions.ykeys = res.keyValuesObj;
        this.chartOptions.labels = res.keyValuesObj;
        this.salesData = res.chartDataValuesObj;
      });
```

After loading the data, my chartOptions object looks like this:
```
{
behaveLikeLine: true
fillOpacity: 0.3
labels:  ["secondrelease", "testprintticket", "total"]
lineColors: ["rgba(151,187,205,0.7)"]
parseTime: false
pointFillColors: ["#FAFAFA"]
pointStrokeColors: ["#CCCCCC"]
resize: true
xkey: "date"
ykeys: ["secondrelease", "testprintticket", "total"]
}
```

and my data object looks like this:
```
[{date: "01.10.2018", secondrelease: 0, testprintticket: 2565, total: 2565},
{date: "02.10.2018", secondrelease: 950, testprintticket: 17503, total: 18453}]
```

Even though the above seem correct, I get the following error:
`raphael.js:5957 Error: <path> attribute d: Expected moveto path command ('M' or 'm'), "L1041.45,309.012…".`

However, if I set the xkeys and labels in the default object initialization it works, but when they are set dynamically i always get the above error. Any help appreciated.

Carol

**Comment by pierresh** [comment]
Hello, 

I suppose you did not use [ and ] for data in the html file.

For your reference, here is my code that works perfectly:

In component.html
```
<div mk-morris-js 	[options]='chart.options'
			[data]='chart.data'
			[type]='chart.type' 
			style="height: 300px; width: 100%;"></div>
```

And in component.ts (my chart is dynamic, it can be any type)
```
[...]

this.charts.push({
	type: type,
	data: d.data.items[a].data,
	options: {
		xkey: 'xkey',
		ykeys: tmp_array,
		labels: tmp_array,
		parseTime: false, 
		gridIntegers: true, 
		colors: this.color_charts,
		lineColors: this.color_charts,
		barColors: this.color_charts,
	}
});

```

**Comment by carol-braileanu** [comment]
I did use [ ] for data and for options in my html file. I even changed my code to match yours:

HTML
`<div mk-morris-js [options]="chart.options" [data]="chart.data" type="Area" style="height: 300px; width: 100%;"></div>
`

TS
```
  public chart: any = { options: this.newChartOptions };

  public get newChartOptions(){
    return JSON.parse(JSON.stringify({
    xkey: 'date',
        ykeys: [],
        labels: [],
        parseTime:false,
        behaveLikeLine: true,
        pointFillColors:['#FAFAFA'],
        pointStrokeColors: ['#CCCCCC'],
        lineColors:['rgba(151,187,205,0.7)'],
        fillOpacity: 0.3,
        resize: true
    }));
  }
[...]

this.eventService.getSalesChart(r['id']).subscribe(res => {
        
        this.chart = { options: {
          xkey: 'date',
              ykeys: res.keyValuesObj,
              labels: res.keyValuesObj,
              parseTime:false,
              behaveLikeLine: true,
              pointFillColors:['#FAFAFA'],
              pointStrokeColors: ['#CCCCCC'],
              lineColors:['rgba(151,187,205,0.7)'],
              fillOpacity: 0.3,
              resize: true
          }, data: res.chartDataValuesObj };
      });
```

When chartOptions is initalized with a **new** object and then replaced with another object, like in the example above, i get the error: 

`raphael.js:5957 Error: <path> attribute d: Expected moveto path command ('M' or 'm'), "L1041.45,309.012…".`

When chartOptions is initalized with a **null** object and then set dynamically, I get the error:

```
ERROR TypeError: Cannot read property 'match' of undefined
    at Object.Morris.parseDate (morris.js:598)
    at Area.<anonymous> (morris.js:231)
    at Area.Morris.Grid.Grid.setData (morris.js:280)
    at MorrisChartDirective.push../node_modules/angular-morris-js/esm5/angular-morris-js.js.MorrisChartDirective.ngOnChanges (angular-morris-js.js:28)
    at checkAndUpdateDirectiveInline (core.js:9246)
    at checkAndUpdateNodeInline (core.js:10514)
    at checkAndUpdateNode (core.js:10476)
    at debugCheckAndUpdateNode (core.js:11109)
    at debugCheckDirectivesFn (core.js:11069)
    at Object.eval [as updateDirectives] (EventOverviewComponent.html:88)
```

Also, the error seems to happen when i set the data.

**Comment by carol-braileanu** [comment]
Here is your problem: 
https://github.com/mika-el/angular-morris-js/blob/dae6c0d17947675b7817d8fb2184ab457cf2d484/src/morris-chart.directive.ts#L15-L37

The options object is only set on ngOnInit, and cannot be modified at a later time. So if I set my Options at any later time it will not load the options object correctly. My workaround was to add an *ngIf to the div that contains the chart and make the chart visible only after the data has been loaded. 

I can make a fix for this if you like, or is this by design?
